# Generated by Django 6.0.6 on 2026-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Galvanised Wire, Barbed Wire", max_length=255
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 2.0mm x 50kg, 800m x 1.8mm, 40m x 1.2m",
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SHEETS", "Roofing Sheets / IBR"),
                            ("WIRE", "Fencing & Wire Products"),
                            ("INSULATION", "Insulation & Membranes"),
                            ("ACCESSORIES", "Roofing Accessories"),
                        ],
                        default="SHEETS",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in USD", max_digits=10
                    ),
                ),
                (
                    "price_note",
                    models.CharField(
                        blank=True,
                        help_text="e.g., wholesale, per 10m roll, per meter",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
